version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: urlshortener-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urlshortenerdb
      MYSQL_USER: urluser
      MYSQL_PASSWORD: urlpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: urlshortener-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: urlshortener-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/urlshortenerdb
      SPRING_DATASOURCE_USERNAME: urluser
      SPRING_DATASOURCE_PASSWORD: urlpassword
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mysql_data: