spring.application.name=urlshortner

# Application
spring.application.name=urlshortener
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username=urluser
spring.datasource.password=urlpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# App config
app.base-url=http://localhost:8080
app.short-code-length=6
app.default-expiry-days=30